blank_issues_enabled: true
contact_links:
  - name: 📥 Download latest version
    url: https://github.com/Yeetus3141/ImagePaste/releases/latest
    about: Make sure you're running the latest version, your bugs may already be fixed.
  - name: 📢 Open a new discussion
    url: https://github.com/Yeetus3141/ImagePaste/discussions/new
    about: If you haven't ready to open an issue yet, question here.
